# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: swift

install: swift package generate-xcodeproj --xcconfig-overrides conf.xcconfig

jobs:
  include:
    # macOS
    - name: macOS 10.14
      osx_image: xcode10.2
      xcode_project: Robin.xcodeproj
      xcode_scheme: Robin-Package
      xcode_destination: platform=macOS
      before_install: echo "MACOSX_DEPLOYMENT_TARGET = 10.14" >> conf.xcconfig
    - name: macOS 10.15
      osx_image: xcode11.4
      xcode_project: Robin.xcodeproj
      xcode_scheme: Robin-Package
      xcode_destination: platform=macOS
      before_install: echo "MACOSX_DEPLOYMENT_TARGET = 10.14" >> conf.xcconfig
    - name: macOS 11.0
      osx_image: xcode12.2
      xcode_project: Robin.xcodeproj
      xcode_scheme: Robin-Package
      xcode_destination: platform=macOS
      before_install: echo "MACOSX_DEPLOYMENT_TARGET = 10.14" >> conf.xcconfig
    # iOS
    - name: iOS 10.3.1
      osx_image: xcode11.1
      xcode_project: Robin.xcodeproj
      xcode_scheme: Robin-Package
      xcode_destination: platform=iOS Simulator,OS=10.3.1,name=iPhone 7
      before_install: echo "IPHONEOS_DEPLOYMENT_TARGET = 10.0" >> conf.xcconfig
    - name: iOS 11.0.1
      osx_image: xcode11.1
      xcode_project: Robin.xcodeproj
      xcode_scheme: Robin-Package
      xcode_destination: platform=iOS Simulator,OS=11.0.1,name=iPhone 8
      before_install: echo "IPHONEOS_DEPLOYMENT_TARGET = 10.0" >> conf.xcconfig
    - name: iOS 12.0
      osx_image: xcode11.1
      xcode_project: Robin.xcodeproj
      xcode_scheme: Robin-Package
      xcode_destination: platform=iOS Simulator,OS=12.0,name=iPhone 8
      before_install: echo "IPHONEOS_DEPLOYMENT_TARGET = 10.0" >> conf.xcconfig
    - name: iOS 13.1
      osx_image: xcode11.1
      xcode_project: Robin.xcodeproj
      xcode_scheme: Robin-Package
      xcode_destination: platform=iOS Simulator,OS=13.1,name=iPhone 8
      before_install: echo "IPHONEOS_DEPLOYMENT_TARGET = 10.0" >> conf.xcconfig
    - name: iOS 14.0.1
      osx_image: xcode12.2
      xcode_project: Robin.xcodeproj
      xcode_scheme: Robin-Package
      xcode_destination: platform=iOS Simulator,OS=14.0.1,name=iPhone 8
      before_install: echo "IPHONEOS_DEPLOYMENT_TARGET = 10.0" >> conf.xcconfig
    # watchOS
    - name: watchOS 6.0
      osx_image: xcode11.1
      before_install: echo "WATCHOS_DEPLOYMENT_TARGET = 3.0" >> conf.xcconfig
      script: set -o pipefail && xcodebuild -project Robin.xcodeproj -scheme Robin-Package -destination platform\=watchOS\ Simulator,OS\=6.0,name\=Apple\ Watch\ Series\ 4\ -\ 40mm build | xcpretty
