# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode10
language: objective-c
xcode_scheme: Robin
xcode_destination: platform=iOS Simulator,OS=10.0,name=iPhone X
