# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c

install: swift package generate-xcodeproj

jobs:
  include:
    # macOS
    - osx_image: xcode10.2
      xcode_project: Robin.xcodeproj
      xcode_scheme: Robin-Package
      xcode_destination: platform=macOS
    - osx_image: xcode11.4
      xcode_project: Robin.xcodeproj
      xcode_scheme: Robin-Package
      xcode_destination: platform=macOS
    - osx_image: xcode12.2
      xcode_project: Robin.xcodeproj
      xcode_scheme: Robin-Package
      xcode_destination: platform=macOS
    # iOS
    - osx_image: xcode10.3
      xcode_project: Robin.xcodeproj
      xcode_scheme: Robin-Package
      xcode_destination: platform=iOS Simulator,OS=12.4,name=iPhone 8
    - osx_image: xcode11.6
      xcode_project: Robin.xcodeproj
      xcode_scheme: Robin-Package
      xcode_destination: platform=iOS Simulator,OS=13.6,name=iPhone 8
    - osx_image: xcode12.2
      xcode_project: Robin.xcodeproj
      xcode_scheme: Robin-Package
      xcode_destination: platform=iOS Simulator,OS=14.2,name=iPhone 8
