# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode10
language: objective-c
script:
- swift package generate-xcodeproj && xcodebuild test -project Robin.xcodeproj -scheme Robin-Package -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone X' ONLY_ACTIVE_ARCH=NO | xcpretty
